#!/bin/sh
#
# Lists untracked `*.get` files and bundles that lack `*.get` files.
#
# Usage: ./list-untracked-bundles
#
# Written in 2010 by Suraj N. Kurapati <https://github.com/sunaku>

git ls-files --others '*bundle/*.get'

git ls-files --others '*bundle/*/' | while read dir; do
  test -f ${dir%/}.get || echo "$dir"
done
