#!/bin/bash -e
#
# Renames existing bundles whose names match the given regular expression.
#
# At the prompt, edit the bundle location and press ENTER to rename it so.
# If you no longer wish to rename the bundle, just press ENTER to skip it.
# If you made a mistake and want to abort the rename, press Control and C.
#
# Usage: ./rename-bundles [OPTIONS_FOR_GREP...] BUNDLE_NAME_REGEXP
#
# Written in 2015 by Suraj N. Kurapati <https://github.com/sunaku>

git ls-files --cached --others '*.get' | grep -i "${@-.}" | while read get; do

  dir=${get%.get}
  read -p "(rename) " -i "$dir" -e rename </dev/tty
  test -z "$rename" -o "$rename" = "$dir" && continue

  for old in "$dir"*; do
    ext=${old##*.}
    test "$ext" = "$old" && unset ext
    new="$rename${ext+.}$ext"
    mkdir -p "${new%/*}"
    git mv "$old" "$new" 2>/dev/null || mv -vi "$old" "$new" </dev/tty
  done

done
