nnoremap <Leader>t/ :setlocal hlsearch!<Return>
nnoremap <Leader>tl :setlocal list!<Return>
nnoremap <Leader>tn :setlocal number!<Return>
nnoremap <Leader>tN :setlocal relativenumber!<Return>
nnoremap <Leader>tp :setlocal paste!<Return>
nnoremap <Leader>ts :setlocal spell!<Return>
nnoremap <Leader>tz :setlocal foldenable!<Return>
nnoremap <Leader>tc :setlocal cursorcolumn!<Return>
nnoremap <Leader>tC :setlocal cursorline!<Return>
